"""
xSHACL Architecture
--------------------
This module defines the core data structures used throughout the xSHACL system,
including constraint violations, justification trees, and context information.
"""

from dataclasses import dataclass, field
from enum import Enum
from typing import Dict, List, Optional


# --- Enums ---
class ViolationType(Enum):
    """Enumeration of different types of SHACL violations."""

    CARDINALITY = "cardinality"
    VALUE_TYPE = "value_type"
    VALUE_RANGE = "value_range"
    PATTERN = "pattern"
    PROPERTY_PAIR = "property_pair"
    LOGICAL = "logical"
    OTHER = "other"


# --- Basic Type Aliases ---
NodeId = str
ShapeId = str


# --- Data Classes ---
@dataclass
class ConstraintViolation:
    """
    Represents a SHACL constraint violation.
    Captures detailed information about the violation for building explanations.
    """

    focus_node: NodeId
    shape_id: ShapeId
    constraint_id: str
    violation_type: ViolationType
    property_path: Optional[str] = None
    value: Optional[str] = None
    message: Optional[str] = None
    severity: Optional[str] = None
    context: Dict = field(default_factory=dict)  


@dataclass
class JustificationNode:
    """Represents a node in a justification tree."""

    statement: str
    type: str  # e.g., "conclusion", "premise", "observation", "inference", "error"
    evidence: Optional[str] = None  # Optional evidence supporting the node
    children: List["JustificationNode"] = field(default_factory=list)

    def add_child(self, child: "JustificationNode"):
        """Adds a child node to this node."""
        self.children.append(child)

    def to_dict(self) -> Dict:
        """Convert node and its children to a dictionary"""
        return {
            "statement": self.statement,
            "type": self.type,
            "evidence": self.evidence,
            "children": [child.to_dict() for child in self.children],
        }


@dataclass
class JustificationTree:
    """Represents a logical justification tree for a SHACL violation."""

    root: JustificationNode
    violation: ConstraintViolation

    def to_dict(self) -> Dict:
        """Convert the entire tree to a dictionary"""
        return {
            "violation": self.violation.__dict__,
            "justification": self.root.to_dict(),
        }


@dataclass
class DomainContext:
    """
    Captures contextual information relevant to a SHACL violation.
    This information is used to enrich the explanations generated by the LLM.
    """

    ontology_fragments: List[str] = field(default_factory=list)
    shape_documentation: List[str] = field(default_factory=list)
    similar_cases: List[Dict] = field(default_factory=list)
    domain_rules: List[str] = field(default_factory=list)


@dataclass
class ExplanationOutput:
    """
    Represents the full output of the xSHACL explanation system for a
    single violation.
    """

    natural_language_explanation: str
    correction_suggestions: List[str] = field(default_factory=list)
    violation: Optional[ConstraintViolation] = None
    justification_tree: Optional[JustificationTree] = None
    retrieved_context: Optional[DomainContext] = None

    def to_dict(self) -> Dict:
        """Convert to a dictionary for JSON output"""
        return {
            "violation": self.violation
            if self.violation
            else None,
            "justification_tree": self.justification_tree.to_dict()
            if self.justification_tree
            else None,
            "retrieved_context": self.retrieved_context
            if self.retrieved_context
            else None,
            "natural_language_explanation": self.natural_language_explanation,
            "correction_suggestions": self.correction_suggestions,
        }
